# Starter pipeline

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - azurebcproject2/*

pool:
  name: Default
  demands:
    - Agent.name -equals azure-vm

stages:
  - stage: dev
    displayName: "Deploy Dev"
    jobs:
      - job: deploy_dev_job
        displayName: "Deploy Dev Job"
        steps:

          # --------------------------------------
          # Install Terraform manually (reliable)
          # --------------------------------------
          - script: |
              sudo apt-get update
              sudo apt-get install -y unzip curl jq ca-certificates
              
              echo "Downloading Terraform..."
              curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.14.1/terraform_1.14.1_linux_amd64.zip

              echo "Extracting Terraform..."
              unzip -o terraform.zip

              echo "Installing Terraform to /usr/local/bin..."
              sudo mv terraform /usr/local/bin/terraform
              sudo chmod +x /usr/local/bin/terraform

              echo "Terraform installed:"
              terraform version
            displayName: "Install Terraform manually"

          # Checkout source code
          - checkout: self

          # --------------------------------------
          # Terraform INIT
          # --------------------------------------

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              installTerraform: false
              workingDirectory: '$(System.DefaultWorkingDirectory)/azurebcproject2/env/dev'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Azure-Service-connection'
              backendAzureRmResourceGroupName: 'tfstate-rg'
              backendAzureRmStorageAccountName: 'tfstatesacct0t123'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'aks/dev.tfstate'

          # --------------------------------------
          # Terraform APPLY
          # --------------------------------------
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              installTerraform: false        # <--- IMPORTANT
              workingDirectory: '$(System.DefaultWorkingDirectory)/azurebcproject2/env/dev'
              commandOptions: '--var-file=dev.tfvars --auto-approve'
              environmentServiceNameAzureRM: 'Azure-Service-connection'
